version: '3.8'

services:
  postgres:
    image: cleisonfmelo/postgres-pg-cron # make sure that you have pg-cron available on whatever postgres service you're running
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: